/*
 * DaDaPush Public API
 *
 * DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 *
 * The version of the OpenAPI document: v1
 * Contact: contacts@dadapush.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct Action {
    /// action button name
    #[serde(rename = "name")]
    pub name: String,
    /// fix value: link
    #[serde(rename = "type")]
    pub _type: String,
    /// action url
    #[serde(rename = "url")]
    pub url: String,
}

impl Action {
    pub fn new(name: String, _type: String, url: String) -> Action {
        Action {
            name: name,
            _type: _type,
            url: url,
        }
    }
}

/// fix value: link
#[derive(Debug, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "link")]
    Link,
}

