/*
 * DaDaPush Public API
 *
 * DaDaPush: Real-time Notifications App Send real-time notifications through our API without coding and maintaining your own app for iOS or Android devices.
 *
 * The version of the OpenAPI document: v1
 * Contact: contacts@dadapush.com
 * Generated by: https://openapi-generator.tech
 */


#[allow(unused_imports)]
use serde_json::Value;


#[derive(Debug, Serialize, Deserialize)]
pub struct MessagePushResponse {
    #[serde(rename = "messageId")]
    pub message_id: i64,
}

impl MessagePushResponse {
    pub fn new(message_id: i64) -> MessagePushResponse {
        MessagePushResponse {
            message_id: message_id,
        }
    }
}


